name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "ci@github.com"
          git config --global user.name "GitHub Actions"
          git clone https://Vineel0508:$HF_TOKEN@huggingface.co/spaces/Vineel0508/Conversational-RAG hf_space
          cp app.py hf_space/
          cp requirements.txt hf_space/
          cp README.md hf_space/
          cp Dockerfile hf_space/
          cd hf_space
          git add .
          git diff --cached --quiet || git commit -m "Deploy from GitHub - ${{ github.sha }}"
          git push
